require('config.treesitter')
require('config.lsp')
require('config.dashboard')
require('config.lspinstall')
require('config.autosave')
require('config.autopairs')
require('config.cmp')
require('config.fzf')
